# These are supported funding model platforms

github: [abhigdrv]
patreon: abhigdrv
open_collective: abhishek-vishwakarma
ko_fi: abhishek_vishwakarma
# tidelift: abhigdrv
# community_bridge: abhigdrv
# liberapay: abhigdrv
# issuehunt: abhigdrv
# otechie: abhigdrv
custom: ['https://www.paypal.me/zxter']
