# These are supported funding model platforms

github: [abhigdrv]
patreon: abhigdrv
open_collective: abhigdrv
ko_fi: abhigdrv
tidelift: abhigdrv
community_bridge: abhigdrv
liberapay: abhigdrv
issuehunt: abhigdrv
otechie: abhigdrv
custom: ['https://www.paypal.me/zxter']
